name: disenounico
description: App MVP para gestión de pedidos - Diseño Único
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase & core
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.16.0

  # Utilities
  provider: ^6.0.5
  cached_network_image: ^3.3.1

  # Image upload (Cloudinary flow)
  image_picker: ^0.8.9
  http: ^1.1.0
  mime: ^1.0.6
  path: ^1.8.3
  http_parser: ^4.0.0
  shared_preferences: ^2.0.15
  firebase_messaging: ^14.6.4
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/image.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/
